project/accounts/urls.py
from django.urls import path
from pywebio.platform.django import webio_view

from .views import login_view, register_view, logout_view
from . import  views

app_name = 'accounts'
#from pywebio.platform.django import webio_view
from django.urls import path


urlpatterns = [
    path('', login_view,name='login'),
    #path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    #path('headblog/', views.index),
    path('rss_list/<username>/<int:page>/', views.rss_list, name='rss_list'),
    path('rss_refresh/<int:rss_id>/', views.rss_refresh, name='rss_refresh'),
    path('rss_list/<username>/posts/<int:id>/',views.detail, name='detail'),
    path('refresh_rss/<username>/', views.refresh_rss, name='refresh_rss'),
    path('<str:username>/archive/<int:page>/',views.rss_archive,name='rss_archive'),
    path('data/<username>', views.data,name='data'),
    path('wordcloud/<username>', views.cloud, name='wordcloud'),
    path('rss_list/<username>/<sourcename>/', views.deleterss, name='delete'),
    path('rss_refresh/<username>/<int:url_id>/', views.addthisurl, name='add'),
    path('<str:username>/archive/<str:tag>/', views.detailtag, name='tag_archive'),
    path('uadmin/',  views.adminop, name='uadmin'),
    path('deleteadmin/<str:username>',  views.deleteuser, name='udelete'),


]

project/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from text import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('rss_reader/', include('rss_reader.urls')),
    #path('text/', views.index),
    #path('', include('login.urls')),
    path('',include('accounts.urls')),
    path('headblog/',include('headblog.urls')),
    path('sqloperate/',include('sqloperate.urls')),



]

project/login/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from  login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rss_reader/', include('rss_reader.urls')),
    path('',views.index1),



]

project/accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class MyUser(AbstractBaseUser):
    email = models.CharField(unique=True,max_length=30)
    name = models.CharField(max_length=30)
    userpass=models.CharField(max_length=30,default='')

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return f'{self.email}'

    def get_full_name(self):
        return f'{self.name}'

    def get_short_name(self):

        return self.name

    def has_module_perms(self, app_label):
        return self.is_staff

class UserFeedInfo(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    link = models.CharField(max_length=255)
    img_src=models.CharField(max_length=255,null=True, blank=True)
    description = models.TextField()
    pub_date = models.TextField()
    expert=models.TextField(default='')
    category=models.TextField(default='',null=True, blank=True)
    sourcename = models.TextField(default='',null=True, blank=True)
    url=models.CharField(default='',null=True, max_length=255)


    def __str__(self):
        return self.title

    def __lt__(self, other):
        """
        定义 UserFeedInfo 对象之间的小于关系，用于排序
        """
        return self.id < other.id

    # # 自定义 get_absolute_url 方法
    # # 记得从 django.urls 中导入 reverse 函数
    # def get_absolute_url(self):
    #     return reverse('headblog:detail', kwargs={'id': self.id})


    def __str__(self):
        return str(self.id)


class UserCommentInfo(models.Model):
    comment = models.TextField()
    user=models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post=models.ForeignKey(UserFeedInfo, on_delete=models.CASCADE)
    datatime=models.TextField()



    # # 自定义 get_absolute_url 方法
    # # 记得从 django.urls 中导入 reverse 函数
    # def get_absolute_url(self):
    #     return reverse('headblog:detail', kwargs={'id': self.id})


    def __str__(self):
        return str(self.id)

project/login/models.py
from django.db import models

# Create your models here.

project/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import MyUser
from .models import UserFeedInfo

class MyLoginForm(AuthenticationForm):
    username = forms.CharField(label='username', max_length=255)
    password = forms.CharField(label='password', max_length=255)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if email and password:
            user = MyUser.objects.filter(email=email).first()
            print("yes!")
            if not user:
                print("no!!~!")
                raise forms.ValidationError('Invalid email or password')
        return cleaned_data





class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(label='Email', max_length=255)
    name = forms.CharField(max_length=255)
    password=forms.CharField(max_length=255)


    class Meta:
        model = MyUser
        fields = ('email', 'name','password1', 'password2')




class RSSFeedForm(forms.ModelForm):
    class Meta:
        model = UserFeedInfo
        fields = ('url',)
        labels = {
            'url': 'RSS URL',
        }
        widgets = {
            'url': forms.URLInput(attrs={'class': 'form-control'}),
        }

project/accounts/views.py
from datetime import datetime
import feedparser
from aip import AipNlp
from bs4 import BeautifulSoup
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.checks import messages
from django.db import transaction
from django.db.models import Count
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
import feedparser
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_POST, require_GET
from numpy import sort
from pywebio.platform.django import webio_view

from .models import UserFeedInfo
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from .forms import MyLoginForm, MyRegistrationForm, RSSFeedForm
from django.contrib.auth import get_user_model
from .models import MyUser, UserFeedInfo
from django.core.exceptions import ValidationError
from rss_reader.models import Feedurl
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
def login_view(request):



    if request.method == 'POST':
        form = MyLoginForm(request=request, data=request.POST)

        form.is_valid()
        email = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        print(email + password)
        if email and password:
            user = MyUser.objects.filter(email=email, userpass=password).first()
        if user is not None:
            login(request, user)
            request.session['username'] = user.name
            return HttpResponseRedirect('/headblog/?username={}'.format(user.name))
        else:

            print("no!!!")
            print(form.errors)
    else:
        form = MyLoginForm()
    return render(request, 'login.html', {'form': form})


# def login_view(request):
#     User = get_user_model()
#     print(User)
#     if request.method == 'POST':
#         form = MyLoginForm(request=request, data=request.POST)
#
#         if form.is_valid():
#             email = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password')
#             print(type(email))
#             user = MyUser.objects.filter(email=email)
#
#             print(user.name)
#
#             # user = authenticate(request=request, email=email, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('/headblog')
#         else:
#             # email = form.cleaned_data.get('username')
#             # password = form.cleaned_data.get('password')
#             # user = MyUser.objects.filter(email=email, userpass=password)
#             # single = user.first()
#             # if user is not None:
#             #     print(single.name)
#             #     login(request, single)
#             #     return redirect('/headblog')
#             #
#             # else:
#             print(form.errors)
#     else:
#         form = MyLoginForm()
#     return render(request, 'login.html', {'form': form})
from rss_reader.models import Feedurl
def remove_emoji(string):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub(r'', string)


def clean_text(text):
    # 只保留中文或英文字符
    pattern = re.compile('[^\u4e00-\u9fa5a-zA-Z]')
    return pattern.sub('', text)
@login_required
def rss_list(request, username,page):


    allurl=Feedurl.objects.all()

    global all_feed_info, sqlitem, url
    APP_ID = '30610004'
    API_KEY = '6gT4lh7DtMW07DQ5cpdpwADC'
    SECRET_KEY = 'N399OPRIYdIBuu92psGcyHYCMnim9GiT'
    users = MyUser.objects.filter(name=username)
    user = users.first()
    id = user.id
    print("USERID"+str(id))
    name=user.name
    categories = []
    source=[]
    # 获取当前用户添加的所有 rss
    rss_feeds =  UserFeedInfo.objects.filter(user=id)[::-1]
    for s in rss_feeds:
        categories.append(s.category)
        source.append(s.sourcename)


    categories=set(categories)
    if " " in categories:
        categories.remove(" ")

    source=set(source)

    rss_feeds = UserFeedInfo.objects.filter(user_id=id)
    category_counts = rss_feeds.exclude(category=" ").values('category').annotate(count=Count('category')).order_by(
        # 统计这些 RSS 源的分类，并按照分类的订阅数量从大到小排序
        '-count')
    top_categories = [c['category'] for c in category_counts[:2]]
    recommended_feeds = UserFeedInfo.objects.filter(category__in=top_categories).order_by('?')[:5]  # 找到订阅数量最多的两个分类
    # 从这两个分类中随机选择一个 RSS 源，并推荐给用户



     # print(categories)
    #获取当前用户的所有标签
    #实现分页

    rss_feeds = UserFeedInfo.objects.filter(user=id)[::-1]
    paginator=Paginator(rss_feeds,10)
    page_obj = paginator.get_page(page)

    #page = request.GET.get('page')
    try:
        feeds = paginator.page(page)
    except PageNotAnInteger:
        feeds = paginator.page(1)
    except EmptyPage:
        feeds = paginator.page(paginator.num_pages)









    if request.method == 'POST':
        form = RSSFeedForm(request.POST)

        form.is_valid()
        # rss_feed = form.save(commit=False)

        url = form.cleaned_data['url']
        print(url)
        feed = feedparser.parse(url)
        entries = feed.entries
        items = []
        for entry in entries:
            item = {}
            item['title'] = entry.title
            item['description'] = entry.description
            item['link'] = entry.link
            currentDateAndTime = datetime.now()
            item['pub_date'] = currentDateAndTime
            item['sourcename'] = feed['feed']['title']
            item['url'] = url
            item['user'] = id
            soup1 = BeautifulSoup(entry.description, features='html.parser')
            # print(type(entry.ti tle))
            img_src = "https://pic.imgdb.cn/item/64087ba7f144a01007bfecf0.png"  # 给变量 img_src 赋一个默认值 None

            img_tag = soup1.find('img')
            if img_tag:
                img_src = img_tag['src']
                # print('Image:', img_src)
            else:
                pass
                # print('Image not found')
            item['img'] = img_src

            soup = BeautifulSoup(item['description'], features="html.parser")
            item['description'] = soup.get_text()
            item['description']=clean_text(item['description'])
            summary = '。'.join(item['description'].split('。')[:1]) + '。'
            item['expert'] = summary
            client = AipNlp(APP_ID, API_KEY, SECRET_KEY)
            item['category'] = " "
            tag = client.topic(entry.title, item['description'])
            tag_item = tag.get('item')
            if tag_item:
                lv1_tag_list = tag_item.get('lv1_tag_list')
                if lv1_tag_list:
                    try:
                        item['category'] = tag['item']['lv1_tag_list'][0]['tag']
                    except KeyError:
                        print("Category not found in tag.")
                        item['category'] = " "

            with transaction.atomic():
                sqlitem = UserFeedInfo(title=entry.title, link=entry.link, img_src=item['img'],
                                       description=soup.get_text(),
                                       pub_date=currentDateAndTime, expert=item['expert'], category=item['category'],
                                       sourcename=item['sourcename'], user_id=id, url=url)
                if UserFeedInfo.objects.filter(title=entry.title, user_id=id):
                    my = UserFeedInfo.objects.filter(title=entry.title)
                    for mysingle in my:
                        pass
                        # print("已经存在"+mysingle.title)
                    pass
                else:
                    sqlitem.save()




            items.append(item)

        # rss_feed.user = request.user.id
        # rss_feed.save()

        # messages.success(request, 'RSS feed added successfully.')
        return redirect(reverse('accounts:rss_list', kwargs={'username': name,'page':1}))

    else:
        form = RSSFeedForm()

    return render(request, 'rss_list.html', {'page_obj': page_obj,'rss_feeds': feeds, 'form': form, 'id': id,'username':name,'page': page,'category':categories,'source':source,'topcate':top_categories,'recommend':recommended_feeds ,'allurl':allurl,'user':user})


@login_required
def rss_refresh(request, rss_id):
    rss_feed = UserFeedInfo.objects.get(id=rss_id)
    rss_feed.refresh()

    # messages.success(request, 'RSS feed refreshed successfully.')
    return redirect(reverse('rss_list'))


def register_view(request):
    if request.method == 'POST':
        # 获取用户提交的表单数据
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']

        # 验证用户是否已经存在
        if MyUser.objects.filter(email=email).exists() or MyUser.objects.filter(name=name).exists():
            messages.error(request, '该邮箱或用户名已经存在')
            return redirect('accounts:register')

        # 创建新用户
        user = MyUser(email=email, name=name,userpass=password,last_login="2022-10-21",is_active=True,is_staff=False)
        user.set_password(password)
        user.save()

        messages.success(request, '注册成功！请登录')
        return redirect('accounts:login')

    return render(request, 'register.html')


def logout_view(request):
    logout(request)
    return redirect('home')

from .models import  UserCommentInfo

project/login/views.py
from django.shortcuts import render

# Create your views here.
def index1(request):
    return render(request,"../templates/login.html")

project/accounts/templates/char.html
  {% block content %}
  <h1>{{ title }}</h1>

  <div class="container">
    {% if chart.fill_bg %}style="background-color: {{ chart.bg_color }}"{% endif %}>
      {{ chart|safe }}
    </div>
  </div>


{% endblock %}

project/accounts/templates/components.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ chart.page_title }}</title>
</head>
<body>

{{ macro.gen_components_content(chart) }}

</body>
</html>

project/accounts/templates/nb_nteract.html
{% import 'macro' as macro %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    {{ macro.render_chart_dependencies(chart) }}
</head>
<body>
    {% for c in chart %}
        {{ macro.render_chart_content(c) }}
    {% endfor %}
</body>
</html>

project/accounts/templates/rss_list.html
{#{% block content %}#}
{##}
{##}
{##}
{#  <div class="row">#}
{#    <div class="col-md-6">#}
{#      <h2>RSS Feeds</h2>#}
{#      <ul>#}
{#        {% for rss_feed in rss_feeds %}#}
{#          <li><a href="{{ rss_feed.url }}">{{ rss_feed.title }}</a></li>#}
{#             <div class="entry-content clearfix">#}
{#              <p>&nbsp&nbsp {{ rss_feed.expert}}</p>#}
{#              <div class="read-more cl-effect-14">#}
{#        {% empty %}#}
{#          <li>No RSS feeds added yet.</li>#}
{#           <p>ID: {{ id }}</p>#}
{#        {% endfor %}#}
{#      </ul>#}
{#      <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit" class="btn btn-primary">Add RSS Feed</button>#}
{#      </form>#}
{#    </div>#}
{#    <div class="col-md-6">#}
{#      <h2>Actions</h2>#}
{#      <a href="{% url 'rss_refresh_all' %}" class="btn btn-primary">Refresh All RSS Feeds</a>#}
{#    </div>#}
{#  </div>#}
{#{% endblock %}#}

{% load static %}
<!DOCTYPE html>

<html>
  <head>
      <title>Rss&amp;聚合</title>

      <!-- meta -->
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- css -->
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
      <link rel="stylesheet" href="{%  static 'css/pace.css' %}">
      <link rel="stylesheet" href="{%  static 'css/custom.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
      <!-- js -->
      <script src=" {%  static 'js/jquery-2.1.3.min.js '%}"></script>
      <script src="{%   static 'js/bootstrap.min.js '%}"></script>
      <script src="{%   static 'js/pace.min.js '%}"></script>
      <script src="{%   static 'js/modernizr.custom.js '%}"></script>
  </head>
  <body>

<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="headindex.html"><b>信息聚合系统</b>&amp;RSS    </a></h1>  <h3>

                    {% if username %}
             <p>欢迎 {{ username }} 用户！</p>
                      {% endif %}

                </h3>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
                      {% with page=page %}
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/headblog" data-hover="首页">首页RSS</a></li>
                            <li class="cl-effect-11"><a href="{% url 'accounts:rss_list' username=username page=page %} " data-hover="我的订阅">我的订阅</a></li>
                             <li class="cl-effect-11"><a href="{%url 'accounts:rss_archive'   username=username page=1 %}" data-hover="文章归档 ">文章归档</a></li>
                            {% endwith %}
                            <li class="cl-effect-11"><a href="{%url 'accounts:data'   username=username   %}" data-hover="文章智能分类">文章智能分类</a></li>
                            <li class="cl-effect-11"><a href="{% url 'accounts:wordcloud' username=username  %}">文章词云</a></li>
                                   {% if user.is_staff %}
                                    <li class="cl-effect-11"><a href="{% url 'accounts:uadmin'   %}" data-hover="管理员界面">管理员界面</a></li>
                              {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
{#                            <input type="search" placeholder="搜索" required>#}
{#                            <button type="submit"><span class="ion-ios-search-strong"></span></button>#}
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>
 <div id="app">

  <div class="content-body">
    <div class="container">

      <div class="row">

        <main class="col-md-8">
          {% for post in rss_feeds %}
                    <article class="post post-{{ post.id }}">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.link }}">{{ post.title }}</a>
                            </h1>
                            <div class="thumbnail1" style="margin-right:400px">
                                <img src="{{ post.img_src }}" alt="缩略图" class="thumbnail1" style="object-fit: cover; width: 400px; height: 200px;  background-position: center center;margin-left:90px;margin-right:400px;">
                            </div>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="{{ post.pub_date }}">{{ post.pub_date }}</time></a></span>
                                <span class="post-author"><a href="#">{{ post.sourcename }}</a></span>
                                <span class="views-count"><a href="{{ post.link }}">到达原文</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p>&nbsp&nbsp {{ post.expert}}</p>
                            <div class="read-more cl-effect-14">
                                <a href="{% url 'accounts:detail' username post.id    %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>
                    {% empty %}
                    <div class="no-post">暂时还没有订阅源！</div>
                    {% endfor %}
                {% if page_obj.has_previous %}
  <a href="{% url 'accounts:rss_list' username=user.name page=page_obj.previous_page_number %}">
    &laquo; Previous
  </a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}
    <span class="current-page">{{ num }}</span>
  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a href="{% url 'accounts:rss_list' username=user.name page=num %}">
      {{ num }}
    </a>
  {% endif %}
{% endfor %}

{% if page_obj.has_next %}
  <a href="{% url 'accounts:rss_list' username=user.name page=page_obj.next_page_number %}">
    Next &raquo;
  </a>
{% endif %}


        </main>
         <aside class="col-md-4">
                    <div class="widget widget-content">
                    <h3 class="widget-title">添加你的rss</h3>
                    <ul>
                        <li>
                            <form method="post" name="add1">
                                    {% csrf_token %}
                                      {{ form.as_p }}
                        <button type="submit" class="btn btn-primary" name="add1">添加您的rss源</button>
                                     </form>

                        </li>
                     <li> <button id="refresh-button" onclick="refreshRSS('{{  username }}')" class="btn btn-primary">刷新您的rss源</button></li>

                                <div class="btn-group">
                         <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                                 没有头绪？看看这里！ <span class="caret"></span></button>
                                                  <ul class="dropdown-menu" role="menu">
                                                      {% for tag in allurl %}
                           <form action="{% url 'accounts:add' username  tag.id %}" method="POST" name="add_button">   {% csrf_token %}<li>   <a href="{{tag.url}}">{{tag.name}}    <button type="submit" class="btn btn-primary btn-xs  "  style="float: right; ">添加</button> </a>      </li> </form>

                                                         {% endfor %}
                                                  </ul>
                                </div>
                    </ul>
                </div>




               <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">Ai生成标签云</h3>
                    <ul>
                        {% for tag in category %}
                        <li>
                            <a href="{%  url 'accounts:tag_archive' username tag  %}">{{ tag }}</a>
                        </li>
                        {% endfor %}
                 </ul>
                </div>
                 <div class="widget widget-category">
                       {% if topcate %}
                         <h3 class="widget-title">你的推荐-由ai标签生成</h3
                         ><p class="text-primary">哦！看起来你最喜欢的内容是{{ topcate.0 }}和{{ topcate.1 }}</p>
                          <p  class="text-primary" > 为你推荐:</p>
                        {% endif %}
                            <ul>
                            {% for s in  recommend  %}



                        <li>
                            <a href="{{ s.link}}">{{s.title}}<span class="post-count">
                                <p class="text-info">{{ s.sourcename }}</p>
                            </span></a>

                        </li>
                          {% endfor %}

                    </ul>


                     <div></div>


                 </div>

                   <div class="widget widget-category">

                    <h3 class="widget-title">你添加的rss源</h3>
                    <ul>
                            {% for s in  source %}



                        <li>
                            <a href="#">{{s}}<span class="post-count"></span></a>
                         <form action="{% url 'accounts:delete' username  s %}" method="post">   {% csrf_token %}<button type="submit" class="btn  btn-sm">删除</button>   </form>
                        </li>
                          {% endfor %}

                    </ul>
                </div>

             </aside>
      </div>

    </div>
  </div>


 </div>



<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="/headindex ">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>



      <!-- 其它内容 -->
<script src="../static/js/script.js"></script>
<script>

const refreshButton = document.querySelector('#refresh-button');
  const refreshMessage = document.querySelector('#refresh-message');
  var username= "{{ username }}"
  refreshButton.addEventListener('click', () => {
    fetch('/refresh_rss/'+username)
      .then(response => response.json())
      .then(data => {

          alert('成功刷新了 ' + data.updated_items + ' 条 RSS 订阅。');
          location.reload()


      })
      .catch(error => {
        refreshMessage.innerHTML = `更新 RSS 订阅失败：${error}`;
      });
  });


</script>

  </body>
</html>

project/accounts/templates/tag_distribution.html
{% load chartit %}
{% block content %}
    {% load chartit %}
    <div id="tag-chart"></div>
    {% chart cht "tag" %}
{% endblock %}