project/accounts/urls.py
from django.urls import path
from pywebio.platform.django import webio_view

from .views import login_view, register_view, logout_view
from . import  views

app_name = 'accounts'
#from pywebio.platform.django import webio_view
from django.urls import path


urlpatterns = [
    path('', login_view,name='login'),
    #path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    #path('headblog/', views.index),
    path('rss_list/<username>/<int:page>/', views.rss_list, name='rss_list'),
    path('rss_refresh/<int:rss_id>/', views.rss_refresh, name='rss_refresh'),
    path('rss_list/<username>/posts/<int:id>/',views.detail, name='detail'),
    path('refresh_rss/<username>/', views.refresh_rss, name='refresh_rss'),
    path('<str:username>/archive/<int:page>/',views.rss_archive,name='rss_archive'),
    path('data/<username>', views.data,name='data'),
    path('wordcloud/<username>', views.cloud, name='wordcloud'),
    path('rss_list/<username>/<sourcename>/', views.deleterss, name='delete'),
    path('rss_refresh/<username>/<int:url_id>/', views.addthisurl, name='add'),
    path('<str:username>/archive/<str:tag>/', views.detailtag, name='tag_archive'),
    path('uadmin/',  views.adminop, name='uadmin'),
    path('deleteadmin/<str:username>',  views.deleteuser, name='udelete'),


]

project/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from text import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('rss_reader/', include('rss_reader.urls')),
    #path('text/', views.index),
    #path('', include('login.urls')),
    path('',include('accounts.urls')),
    path('headblog/',include('headblog.urls')),
    path('sqloperate/',include('sqloperate.urls')),



]

project/headblog/urls.py
from headblog import views


from django.urls import path, include


app_name = 'headblog'
urlpatterns = [

    path('',views.index),
    path('posts/<int:id>/', views.detail, name='detail'),
]

project/login/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from  login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rss_reader/', include('rss_reader.urls')),
    path('',views.index1),



]

project/accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class MyUser(AbstractBaseUser):
    email = models.CharField(unique=True,max_length=30)
    name = models.CharField(max_length=30)
    userpass=models.CharField(max_length=30,default='')

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return f'{self.email}'

    def get_full_name(self):
        return f'{self.name}'

    def get_short_name(self):

        return self.name

    def has_module_perms(self, app_label):
        return self.is_staff

class UserFeedInfo(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    link = models.CharField(max_length=255)
    img_src=models.CharField(max_length=255,null=True, blank=True)
    description = models.TextField()
    pub_date = models.TextField()
    expert=models.TextField(default='')
    category=models.TextField(default='',null=True, blank=True)
    sourcename = models.TextField(default='',null=True, blank=True)
    url=models.CharField(default='',null=True, max_length=255)


    def __str__(self):
        return self.title

    def __lt__(self, other):
        """
        定义 UserFeedInfo 对象之间的小于关系，用于排序
        """
        return self.id < other.id

    # # 自定义 get_absolute_url 方法
    # # 记得从 django.urls 中导入 reverse 函数
    # def get_absolute_url(self):
    #     return reverse('headblog:detail', kwargs={'id': self.id})


    def __str__(self):
        return str(self.id)


class UserCommentInfo(models.Model):
    comment = models.TextField()
    user=models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post=models.ForeignKey(UserFeedInfo, on_delete=models.CASCADE)
    datatime=models.TextField()



    # # 自定义 get_absolute_url 方法
    # # 记得从 django.urls 中导入 reverse 函数
    # def get_absolute_url(self):
    #     return reverse('headblog:detail', kwargs={'id': self.id})


    def __str__(self):
        return str(self.id)

project/headblog/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
from django.utils import timezone

class FeedInfo(models.Model):
    title = models.CharField(max_length=250)
    link = models.CharField(max_length=255)
    img_src=models.CharField(max_length=255)
    description = models.TextField()
    pub_date = models.TextField()
    expert=models.TextField(default='')


    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse('headblog:detail', kwargs={'id': self.id})


    def __str__(self):
        return str(self.id)

project/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import MyUser
from .models import UserFeedInfo

class MyLoginForm(AuthenticationForm):
    username = forms.CharField(label='username', max_length=255)
    password = forms.CharField(label='password', max_length=255)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if email and password:
            user = MyUser.objects.filter(email=email).first()
            print("yes!")
            if not user:
                print("no!!~!")
                raise forms.ValidationError('Invalid email or password')
        return cleaned_data





class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(label='Email', max_length=255)
    name = forms.CharField(max_length=255)
    password=forms.CharField(max_length=255)


    class Meta:
        model = MyUser
        fields = ('email', 'name','password1', 'password2')




class RSSFeedForm(forms.ModelForm):
    class Meta:
        model = UserFeedInfo
        fields = ('url',)
        labels = {
            'url': 'RSS URL',
        }
        widgets = {
            'url': forms.URLInput(attrs={'class': 'form-control'}),
        }

project/headblog/views.py
from django.shortcuts import render, get_object_or_404
from  accounts.models import  MyUser
from  rss_reader.models import FeedInfo
# Create your views here.
def index(request):
    #username = request.GET.get('username', None)  #临时name
    username = request.session.get('username')
    user = MyUser.objects.get(name=username)
    user_id = user.id
    page=1




    return render(request, "headindex.html", {'username': username,'user_id':user_id,'page':page})



def detail(request, id):
    post = get_object_or_404(FeedInfo, id=id)

    print(post)
    return render(request, 'detail.html', context={'post': post})

project/headblog/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
     <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
      <link rel="stylesheet" href="{%  static 'css/pace.css' %}">
      <link rel="stylesheet" href="{%  static 'css/custom.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
      <!-- js -->
      <script src=" {%  static 'js/jquery-2.1.3.min.js '%}"></script>
      <script src="{%   static 'js/bootstrap.min.js '%}"></script>
      <script src="{%   static 'js/pace.min.js '%}"></script>
      <script src="{%   static 'js/modernizr.custom.js '%}"></script>
</head>

<body id="single">
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                           <li class="cl-effect-11"><a href="/headblog" data-hover="首页">首页rss</a></li>
                            <li class="cl-effect-11"><a href="/text" data-hover="我的 ">我的rss</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="rss ">rss智能分类</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系 ">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                <article class="post post-{{ post.id }}">
                 <header class="entry-header">
                  <h1 class="entry-title">{{ post.title }}</h1>
                    <div class="entry-meta">
                     <span class="post-category"><a href="#">{{ post.category }}</a></span>
                             <span class="post-date"><a href="#"><time class="entry-date"
                                                datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                           <span class="post-author"><a href="#">{{ post.author }}</a></span>
                          <span class="comments-link"><a href="#">4 评论</a></span>
                               <span class="views-count"><a href="#">588 阅读</a></span>
                </div>
  </header>
  <div class="entry-content clearfix">
    &nbsp;&nbsp;&nbsp;{{ post.description }}
  </div>
</article>
{#                <section class="comment-area" id="comment-area">#}
{#                    <hr>#}
{#                    <h3>发表评论</h3>#}
{#                    <form action="#" method="post" class="comment-form">#}
{#                        <div class="row">#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_name">名字：</label>#}
{#                                <input type="text" id="id_name" name="name" required>#}
{#                            </div>#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_email">邮箱：</label>#}
{#                                <input type="email" id="id_email" name="email" required>#}
{#                            </div>#}
{#                            <div class="col-md-4">#}
{#                                <label for="id_url">网址：</label>#}
{#                                <input type="text" id="id_url" name="url">#}
{#                            </div>#}
{#                            <div class="col-md-12">#}
{#                                <label for="id_comment">评论：</label>#}
{#                                <textarea name="comment" id="id_comment" required></textarea>#}
{#                                <button type="submit" class="comment-btn">发表</button>#}
{#                            </div>#}
{#                        </div>    <!-- row -->#}
{#                    </form>#}
{#                    <div class="comment-list-panel">#}
{#                        <h3>评论列表，共 <span>4</span> 条评论</h3>#}
{#                        <ul class="comment-list list-unstyled">#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">追梦人物</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月12日 14:56</time>#}
{#                                <div class="text">#}
{#                                    文章观点又有道理又符合人性，这才是真正为了表达观点而写，不是为了迎合某某知名人士粉丝而写。我觉得如果琼瑶是前妻，生了三孩子后被一不知名的女人挖了墙角，我不信谁会说那个女人是追求真爱，说同情琼瑶骂小三的女人都是弱者。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">zmrenwu</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月11日 23:56</time>#}
{#                                <div class="text">#}
{#                                    本能有可能会冲破格局，但格局有时候也会拘住本能。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">蝙蝠侠</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月9日 8:56</time>#}
{#                                <div class="text">#}
{#                                    其实真理一般是属于沉默的大多数的。那些偏激的观点只能吸引那些同样偏激的人。前几年琼瑶告于妈抄袭，大家都表示大快人心，说明吃瓜观众都只是就事论事，并不是对琼瑶有偏见。#}
{#                                </div>#}
{#                            </li>#}
{#                            <li class="comment-item">#}
{#                                <span class="nickname">长江七号</span>#}
{#                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年2月12日 12:56</time>#}
{#                                <div class="text">#}
{#                                    观点我很喜欢！就是哎嘛本来一清二楚的，来个小三小四乱七八糟一团乱麻夹缠不清，简直麻烦要死#}
{#                                </div>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </section>#}
{#            </main>#}
{#            <aside class="col-md-4">#}
{#                <div class="widget widget-content">#}
{#                    <h3 class="widget-title">文章目录</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">教程特点</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">谁适合这个教程</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">在线预览</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">资源列表</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">获取帮助</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="widget widget-recent-posts">#}
{#                    <h3 class="widget-title">最新文章</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django 博客开发入门教程：前言</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">部署 Django 博客</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="widget widget-archives">#}
{#                    <h3 class="widget-title">归档</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">2017 年 5 月</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">2017 年 4 月</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">2017 年 3 月</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="widget widget-category">#}
{#                    <h3 class="widget-title">分类</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="widget widget-tag-cloud">#}
{#                    <h3 class="widget-title">标签云</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Python</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Java</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">笔记</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">文档</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">AngularJS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">CSS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">JavaScript</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Snippet</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">jQuery</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="rss">#}
{#                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>#}
{#                </div>#}
{#            </aside>#}

        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - Collect from <a href="http://www.cssmoban.com/"
                                                                  target="_blank" title="模板之家">模板之家</a>
                    - Modified by <a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>


<script src="../static/js/script.js"></script>
</body>
</html>

project/headblog/templates/headindex.html
<!DOCTYPE html>
<html>
  <head>
      <title>Rss&amp;聚合</title>

      <!-- meta -->
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- css -->
      <link rel="stylesheet" href="../static/css/bootstrap.min.css">
      <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
      <link rel="stylesheet" href="../static/css/pace.css">
      <link rel="stylesheet" href="../static/css/custom.css">
<script src="https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
      <!-- js -->
      <script src="../static/js/jquery-2.1.3.min.js"></script>
      <script src="../static/js/bootstrap.min.js"></script>
      <script src="../static/js/pace.min.js"></script>
      <script src="../static/js/modernizr.custom.js"></script>
  </head>
  <body>

<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="headindex.html"><b>Rss</b> &amp;聚合      </a></h1>
                <h3>
                    {% if username %}
             <p>欢迎 {{ username }} {{user_id}} 用户！</p>
                      {% endif %}

                </h3>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="/headblog" data-hover="首页">首页rss</a></li>
                            <li class="cl-effect-11"><a href="{% url 'accounts:rss_list' username=user.name page=page %}">我的rss</a></li>

{#                            <li class="cl-effect-11"><a href="about.html" data-hover="rss ">rss智能分类和数据分析</a></li>#}
{#                            <li class="cl-effect-11"><a href="{% url 'accounts:rss_refresh' rss_id=user_id %}">Refresh</a></li>#}
                            <li class="cl-effect-11"><button id="refresh-btn">首页刷新</button></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>
 <div id="app">
{% verbatim %}
  <div class="content-body">
    <div class="container">

      <div class="row">

        <main class="col-md-8">
          <article class="post post-{{ post.id }}" v-for="post in feeds" :key="post.id">
            <header class="entry-header">
              <h1 class="entry-title">
                <a :href="post.link">{{ post.title }}</a>
              </h1>
                <div class="thumbnail1" style="margin-right:400px">
                    <img :src="post.img_src" alt="缩略图" class="thumbnail1" style="object-fit: cover; width: 400px; height: 200px;  background-position: center center;margin-left:90px;margin-right:400px; /* 图片在容器中心显示 */" >
                </div>
              <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          :datetime="post.pub_date">{{post.pub_date}}</time></a></span>
                <span class="post-author"><a href="#">{{ post.title }}</a></span>

                <span class="views-count"><a :href="post.link">到达原文</a></span>
              </div>
            </header>
            <div class="entry-content clearfix">
              <p>&nbsp&nbsp {{ post.expert}}</p>
              <div class="read-more cl-effect-14">

                <a v-bind:href="'/headblog/posts/' + post.id + '/'" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                   {% endverbatim %}
              </div>
            </div>
          </article>
          <div class="no-post" v-if="!feeds.length">暂时还没有订阅源！</div>


        </main>
         <aside class="col-md-4">


                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>

             </aside>    ##添加标签页
      </div>

    </div>
  </div>


 </div>



<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2023<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家"> keke</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">keke</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="/headindex ">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>



      <!-- 其它内容 -->
<script src="../static/js/script.js"></script>
<script>
    // 获取刷新按钮元素
const refreshBtn = document.getElementById('refresh-btn');

// 监听点击事件
refreshBtn.addEventListener('click', () => {
  // 发送 AJAX 请求
  const xhr = new XMLHttpRequest();
  xhr.open('GET', '/rss_reader');
  xhr.onload = () => {
    if (xhr.status === 200) {
      // 刷新成功，重新加载页面
      location.reload();
    } else {
      // 刷新失败，提示错误信息
      alert('刷新失败！');
    }
  };
  xhr.send();
});




      var app = new Vue({
      el: '#app',
       data() {
          return {
           feeds:[],
           post: {
        id: 1,
        expert: '这是文章内容',
      },



       }
},



      created() {
    axios.get('/sqloperate')
      .then(response => {
        this.feeds = response.data.reverse();
        console.log(response.data)
      })
      .catch(error => {
        console.log(error);
      });
  },
  mounted() {
    // 可以在这里对渲染后的组件进行操作
  }



  });

</script>
  </body>
</html>